language: python
python:
    - "2.7"
env:
    - DJANGO_PACKAGE="Django>=1.4,<=1.5"
    - DJANGO_PACKAGE="Django>=1.5,<=1.6"
    - DJANGO_PACKAGE="Django>=1.6,<=1.7"
    - DJANGO_PACKAGE="Django>=1.7,<=1.8"
    - DJANGO_PACKAGE="Django>=1.8,<=1.9"
install:
  - echo $DJANGO_PACKAGE
  - pip install $DJANGO_PACKAGE
  - pip freeze
script: python system_globals_project/manage.py test system_globals
